/*
 * Copyright 2023-2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef MODELS_TFLITE_MODEL_TENSORARENA_CONFIG_H_
#define MODELS_TFLITE_MODEL_TENSORARENA_CONFIG_H_

#include "model_configuration.h"

/* The size of Tensor Arena buffer for TensorFlowLite-Micro */
#ifndef HAL_TFLM_TENSOR_ARENA_SIZE_B

/* Minimum required arena size for models */
#if MODEL_QUANTIZED
#if (SELECTED_MODEL == MODEL_CNN)
#define HAL_TFLM_TENSOR_ARENA_SIZE_B 3744
#elif (SELECTED_MODEL == MODEL_LCNN)
#define HAL_TFLM_TENSOR_ARENA_SIZE_B 3200
#elif (SELECTED_MODEL == MODEL_MLP)
#define HAL_TFLM_TENSOR_ARENA_SIZE_B 2816
#elif (SELECTED_MODEL == MODEL_LRESNET)
#define HAL_TFLM_TENSOR_ARENA_SIZE_B 9120
#endif
#else
#if (SELECTED_MODEL == MODEL_CNN)
#define HAL_TFLM_TENSOR_ARENA_SIZE_B 9216
#elif (SELECTED_MODEL == MODEL_LCNN)
#define HAL_TFLM_TENSOR_ARENA_SIZE_B 6560
#elif (SELECTED_MODEL == MODEL_MLP)
#define HAL_TFLM_TENSOR_ARENA_SIZE_B 3824
#elif (SELECTED_MODEL == MODEL_LRESNET)
#define HAL_TFLM_TENSOR_ARENA_SIZE_B 26768
#endif
#endif

#endif // HAL_TFLM_TENSOR_ARENA_SIZE_B

#endif /* MODELS_TFLITE_MODEL_TENSORARENA_CONFIG_H_ */
