/*
 * Copyright 2020-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 0.9.6
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitLpuartPins();
    /* SD card GPIO initialization */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_AD_32_GPIO_MUX3_IO31,       /* GPIO_AD_32 is configured as GPIO_MUX3_IO31 */
              0U);                                    /* Software Input On Field: Input Path is determined by functionality */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_AD_34_USDHC1_VSELECT,       /* GPIO_AD_34 is configured as USDHC1_VSELECT */
              0U);                                    /* Software Input On Field: Input Path is determined by functionality */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_AD_35_GPIO10_IO02,          /* GPIO_AD_35 is configured as GPIO10_IO02 */
              0U);                                    /* Software Input On Field: Input Path is determined by functionality */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_SD_B1_00_USDHC1_CMD,        /* GPIO_SD_B1_00 is configured as USDHC1_CMD */
              1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_00 */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_SD_B1_01_USDHC1_CLK,        /* GPIO_SD_B1_01 is configured as USDHC1_CLK */
              1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_01 */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_SD_B1_02_USDHC1_DATA0,      /* GPIO_SD_B1_02 is configured as USDHC1_DATA0 */
              1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_02 */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_SD_B1_03_USDHC1_DATA1,      /* GPIO_SD_B1_03 is configured as USDHC1_DATA1 */
              1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_03 */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_SD_B1_04_USDHC1_DATA2,      /* GPIO_SD_B1_04 is configured as USDHC1_DATA2 */
              1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_04 */
          IOMUXC_SetPinMux(
              IOMUXC_GPIO_SD_B1_05_USDHC1_DATA3,      /* GPIO_SD_B1_05 is configured as USDHC1_DATA3 */
              1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_05 */
          IOMUXC_GPR->GPR43 = ((IOMUXC_GPR->GPR43 &
            (~(IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH_MASK))) /* Mask bits to zero which are setting */
              | IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH(0x8000U) /* GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: 0x8000U */
            );
          IOMUXC_SetPinConfig(
              IOMUXC_GPIO_SD_B1_00_USDHC1_CMD,        /* GPIO_SD_B1_00 PAD functional properties : */
              0x04U);                                 /* PDRV Field: high drive strength
                                                         Pull Down Pull Up Field: Internal pullup resistor enabled
                                                         Open Drain Field: Disabled
                                                         Domain write protection: Both cores are allowed
                                                         Domain write protection lock: Neither of DWP bits is locked */
          IOMUXC_SetPinConfig(
              IOMUXC_GPIO_SD_B1_01_USDHC1_CLK,        /* GPIO_SD_B1_01 PAD functional properties : */
              0x0CU);                                 /* PDRV Field: high drive strength
                                                         Pull Down Pull Up Field: No Pull
                                                         Open Drain Field: Disabled
                                                         Domain write protection: Both cores are allowed
                                                         Domain write protection lock: Neither of DWP bits is locked */
          IOMUXC_SetPinConfig(
              IOMUXC_GPIO_SD_B1_02_USDHC1_DATA0,      /* GPIO_SD_B1_02 PAD functional properties : */
              0x04U);                                 /* PDRV Field: high drive strength
                                                         Pull Down Pull Up Field: Internal pullup resistor enabled
                                                         Open Drain Field: Disabled
                                                         Domain write protection: Both cores are allowed
                                                         Domain write protection lock: Neither of DWP bits is locked */
          IOMUXC_SetPinConfig(
              IOMUXC_GPIO_SD_B1_03_USDHC1_DATA1,      /* GPIO_SD_B1_03 PAD functional properties : */
              0x04U);                                 /* PDRV Field: high drive strength
                                                         Pull Down Pull Up Field: Internal pullup resistor enabled
                                                         Open Drain Field: Disabled
                                                         Domain write protection: Both cores are allowed
                                                         Domain write protection lock: Neither of DWP bits is locked */
          IOMUXC_SetPinConfig(
              IOMUXC_GPIO_SD_B1_04_USDHC1_DATA2,      /* GPIO_SD_B1_04 PAD functional properties : */
              0x04U);                                 /* PDRV Field: high drive strength
                                                         Pull Down Pull Up Field: Internal pullup resistor enabled
                                                         Open Drain Field: Disabled
                                                         Domain write protection: Both cores are allowed
                                                         Domain write protection lock: Neither of DWP bits is locked */
          IOMUXC_SetPinConfig(
              IOMUXC_GPIO_SD_B1_05_USDHC1_DATA3,      /* GPIO_SD_B1_05 PAD functional properties : */
              0x04U);                                 /* PDRV Field: high drive strength
                                                         Pull Down Pull Up Field: Internal pullup resistor enabled
                                                         Open Drain Field: Disabled
                                                         Domain write protection: Both cores are allowed
                                                         Domain write protection lock: Neither of DWP bits is locked */
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLpuartPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: M15, peripheral: LPUART1, signal: RXD, pin_signal: GPIO_AD_25}
  - {pin_num: L13, peripheral: LPUART1, signal: TXD, pin_signal: GPIO_AD_24}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLpuartPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLpuartPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_24_LPUART1_TXD,          /* GPIO_AD_24 is configured as LPUART1_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_25_LPUART1_RXD,          /* GPIO_AD_25 is configured as LPUART1_RXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPI2C1_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: R15, peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_AD_08, software_input_on: Enable, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper,
    open_drain: Enable, drive_strength: Normal, slew_rate: Slow}
  - {pin_num: R16, peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_AD_09, software_input_on: Enable, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper,
    open_drain: Enable, drive_strength: Normal, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C1_InitPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPI2C1_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

//  IOMUXC_SetPinMux(
//          IOMUXC_GPIO_AD_08_GPIO9_IO07,           /* GPIO_AD_08 is configured as LPI2C1_SCL */
//      0U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_08 */
//  IOMUXC_SetPinMux(
//          IOMUXC_GPIO_AD_08_GPIO9_IO07,           /* GPIO_AD_09 is configured as LPI2C1_SDA */
//      0U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_09 */
//  IOMUXC_SetPinConfig(
//          IOMUXC_GPIO_AD_08_GPIO9_IO07,           /* GPIO_AD_08 PAD functional properties : */
//      0x00U);                                 /* Slew Rate Field: Slow Slew Rate
//                                                 Drive Strength Field: normal drive strength
//                                                 Pull / Keep Select Field: Pull Disable, Highz
//                                                 Pull Up / Down Config. Field: Weak pull down
//                                                 Open Drain Field: Enabled
//                                                 Domain write protection: Both cores are allowed
//                                                 Domain write protection lock: Neither of DWP bits is locked */
//  IOMUXC_SetPinConfig(
//          IOMUXC_GPIO_AD_08_GPIO9_IO07,           /* GPIO_AD_09 PAD functional properties : */
//      0x00U);                                 /* Slew Rate Field: Slow Slew Rate
//                                                 Drive Strength Field: normal drive strength
//                                                 Pull / Keep Select Field: Pull Disable, Highz
//                                                 Pull Up / Down Config. Field: Weak pull down
//                                                 Open Drain Field: Enabled
//                                                 Domain write protection: Both cores are allowed
//                                                 Domain write protection lock: Neither of DWP bits is locked */

  /* GPIO configuration on GPIO_AD_04 (pin M13) */
//  gpio_pin_config_t gpio9_pinM13_config = {
//      .direction = kGPIO_DigitalOutput,
//      .outputLogic = 0U,
//      .interruptMode = kGPIO_NoIntmode
//  };
  /* Initialize GPIO functionality on GPIO_AD_04 (pin M13) */
//  GPIO_PinInit(GPIO9, 7U, &gpio9_pinM13_config);
//  GPIO_PinInit(GPIO9, 8U, &gpio9_pinM13_config);

//  IOMUXC_SetPinMux(
//          IOMUXC_GPIO_AD_08_GPIO9_IO07,           /* GPIO_AD_04 is configured as GPIO9_IO03 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */

//  IOMUXC_SetPinMux(
//          IOMUXC_GPIO_AD_09_GPIO9_IO08,           /* GPIO_AD_04 is configured as GPIO9_IO03 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */

//  for(int i = 0xFFFFFFF/8; i--; i>0);
//  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */


  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_08_LPI2C1_SCL,           /* GPIO_AD_08 is configured as LPI2C1_SCL */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_08 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_09_LPI2C1_SDA,           /* GPIO_AD_09 is configured as LPI2C1_SDA */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_AD_09 */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_08_LPI2C1_SCL,           /* GPIO_AD_08 PAD functional properties : */
      0x18U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_09_LPI2C1_SDA,           /* GPIO_AD_09 PAD functional properties : */
      0x18U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: normal drive strength
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Enabled
                                                 Domain write protection: Both cores are allowed
                                                 Domain write protection lock: Neither of DWP bits is locked */

//  /*
//   * Pull-up enable for SA0 pin on the FRDM-STBI-A8974 shield
//   * Without this workaround the sensor cannot be properly initialized
//   */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_AD_31_GPIO9_IO30,           /* GPIO_AD_31 is configured as GPIO9_IO30 */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//
//  IOMUXC_SetPinConfig(
//      IOMUXC_GPIO_AD_31_GPIO9_IO30,           /* GPIO_AD_31 PAD functional properties : */
//      0x0CU);                                 /* Slew Rate Field: Slow Slew Rate
//                                                 Drive Strength Field: normal drive strength
//                                                 Pull / Keep Select Field: Pull Enable
//                                                 Pull Up / Down Config. Field: Weak pull up
//                                                 Open Drain Field: Disabled
//                                                 Domain write protection: Both cores are allowed
//                                                 Domain write protection lock: Neither of DWP bits is locked */
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPI2C1_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: R15, peripheral: GPIO3, signal: 'gpio_mux_io, 07', pin_signal: GPIO_AD_08, software_input_on: Disable}
  - {pin_num: R16, peripheral: GPIO3, signal: 'gpio_mux_io, 08', pin_signal: GPIO_AD_09, software_input_on: Disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C1_DeinitPins, assigned for the Cortex-M7F core.
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPI2C1_DeinitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_08_GPIO_MUX3_IO07,       /* GPIO_AD_08 is configured as GPIO_MUX3_IO07 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_09_GPIO_MUX3_IO08,       /* GPIO_AD_09 is configured as GPIO_MUX3_IO08 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_GPR->GPR42 = ((IOMUXC_GPR->GPR42 &
    (~(IOMUXC_GPR_GPR42_GPIO_MUX3_GPIO_SEL_LOW_MASK))) /* Mask bits to zero which are setting */
      | IOMUXC_GPR_GPR42_GPIO_MUX3_GPIO_SEL_LOW(0x00U) /* GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: 0x00U */
    );
}


/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
